### ISSUE TITLE
Tutorial chart rendering past screen edge

### ISSUE THREAD

**Issue by alandotcom** [FormidableLabs/victory-tutorial#1]
Just started looking at this project. Great work! If I knew what was happening I'd try to fix it. But here are two screenshots of what this looks like when I start the project on a 13in Macbook Pro Retina

Fullscreen:
![screen shot 2017-02-09 at 11 01 46 am](https://cloud.githubusercontent.com/assets/1812196/22798550/5e83441e-eeb7-11e6-91b6-1e814a5e03ad.png)

Less than half screen width
![screen shot 2017-02-09 at 11 02 04 am](https://cloud.githubusercontent.com/assets/1812196/22798562/689512f2-eeb7-11e6-9fbc-75a066e85684.png)

**Comment by boygirl** [comment]
@lumberj Victory renders responsive containers by default with `width: "100%", height: "auto"`, so this is expected behavior given that the container it renders in does not have any set dimensions. This tutorial is used verbatim in our docs, and rendered in playgrounds, where they scale correctly given these styles. Check it out here instead: http://formidable.com/open-source/victory/docs
